//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyPodinfo) DeepCopyInto(out *MyPodinfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyPodinfo.
func (in *MyPodinfo) DeepCopy() *MyPodinfo {
	if in == nil {
		return nil
	}
	out := new(MyPodinfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyPodinfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyPodinfoImage) DeepCopyInto(out *MyPodinfoImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyPodinfoImage.
func (in *MyPodinfoImage) DeepCopy() *MyPodinfoImage {
	if in == nil {
		return nil
	}
	out := new(MyPodinfoImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyPodinfoList) DeepCopyInto(out *MyPodinfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyPodinfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyPodinfoList.
func (in *MyPodinfoList) DeepCopy() *MyPodinfoList {
	if in == nil {
		return nil
	}
	out := new(MyPodinfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyPodinfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyPodinfoRedis) DeepCopyInto(out *MyPodinfoRedis) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyPodinfoRedis.
func (in *MyPodinfoRedis) DeepCopy() *MyPodinfoRedis {
	if in == nil {
		return nil
	}
	out := new(MyPodinfoRedis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyPodinfoResource) DeepCopyInto(out *MyPodinfoResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyPodinfoResource.
func (in *MyPodinfoResource) DeepCopy() *MyPodinfoResource {
	if in == nil {
		return nil
	}
	out := new(MyPodinfoResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyPodinfoSpec) DeepCopyInto(out *MyPodinfoSpec) {
	*out = *in
	out.Resources = in.Resources
	out.Image = in.Image
	out.Redis = in.Redis
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyPodinfoSpec.
func (in *MyPodinfoSpec) DeepCopy() *MyPodinfoSpec {
	if in == nil {
		return nil
	}
	out := new(MyPodinfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyPodinfoStatus) DeepCopyInto(out *MyPodinfoStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyPodinfoStatus.
func (in *MyPodinfoStatus) DeepCopy() *MyPodinfoStatus {
	if in == nil {
		return nil
	}
	out := new(MyPodinfoStatus)
	in.DeepCopyInto(out)
	return out
}
