# permissions for end users to edit mypodinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mypodinfo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mypodinfo
    app.kubernetes.io/part-of: mypodinfo
    app.kubernetes.io/managed-by: kustomize
  name: mypodinfo-editor-role
rules:
- apiGroups:
  - app.cproject.domain
  resources:
  - mypodinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.cproject.domain
  resources:
  - mypodinfoes/status
  verbs:
  - get
