---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.cproject.domain
  resources:
  - mypodinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.cproject.domain
  resources:
  - mypodinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - app.cproject.domain
  resources:
  - mypodinfoes/status
  verbs:
  - get
  - patch
  - update
