apiVersion: app.cproject.domain/v1
kind: MyPodinfo
metadata:
  labels:
    app.kubernetes.io/name: mypodinfo
    app.kubernetes.io/instance: mypodinfo-sample
    app.kubernetes.io/part-of: mypodinfo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mypodinfo
  name: mypodinfo-sample
spec:
  replicaCount: 2
  resources:
    memoryLimit: 63MB
    cpuRequest: 100m
  image:
    image: "stefanprodan/podinfo"
    name: "podinfo"
  redis: 
    enabled: "true"
