apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mypodinfo-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]