apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mypodinfo-rolebinding
subjects:
- kind: User
  name: system:serviceaccount:mypodinfo-system:mypodinfo-controller-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: mypodinfo-role
  apiGroup: rbac.authorization.k8s.io